{% set name = "bcolz" %}
{% set version = "1.2.1" %}
{% set sha256 = "c017d09bb0cb5bbb07f2ae223a3f3638285be3b574cb328e91525b2880300bd1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools >18.0
    - setuptools_scm >1.5.4
    - cython >=0.22
    - numpy
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numexpr >=2.5.2
    - dask >=0.9.0
    - pandas
    - pytables

test:
  requires:
    - mock
  imports:
    - bcolz
  commands:
    - python -c"import bcolz; bcolz.test(heavy=True)"
    - python -c"import bcolz; assert set(bcolz.blosc_compressor_list()) == set(['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib', 'zstd'])"

about:
  home: http://github.com/Blosc/bcolz
  license: MIT
  license_family: MIT
  license_file: LICENSES/BCOLZ.txt
  summary: 'A columnar data container that can be compressed'
  doc_url: http://bcolz.blosc.org/
  dev_url: http://github.com/Blosc/bcolz

extra:
  recipe-maintainers:
    - alimanfoo
    - FrancescAlted
    - CarstVaartjes
