travis:
  secure:
    BINSTAR_TOKEN: L6KE0+E9z3vksmVajqoXjGQxjrSwqFhNWXuZN/430IT0tWPZsM0mZgYKkrrLlOM1VDn3BbNg7NwjGL6DuT2P8K7dywjRTFgcOi9cwdxdxxgg8wgxb5154zoot9uHdyWf6OhhZpOQnuvhTyBs8bQXJMEp9Ko9hEVYMZPuRX0yodFPW+jTrcc3i2ZBU0Aj/qAEXy/VRT/JQbB8LQF9fRLynMGHStE8aBbkiuXyjoQNW22jk5+0fRJ0YUix1PP/Cmsmp88Tn1qEBkr/7EVVRQtHQK83uM73vy5utiGvWa2shRiDInNjFuyFdEXrjVekfExPjUtZkC4fID+Y4UD/YR4becCTyIcnLFeZc95stoRnGpuFD2bbkxgaWJ5vv7kY/nkLjfP/D6zd8kzdaogLAVTCTPhCFlOifypwPFsf7t0YkJZnf5aDPE03Jhq2bj20a/SdLgV5M8NNc1g9fiLxa6RKgPOTIOqYBfu4eM0+3GhZDOjnmPJQJ+HfHtrTQumDT6AuP3geRI0mT+eh6reXRx0+0/1fnZtTLXrYJIn3sALCwA/evYYvb4n0zP2s0jc+p2N13KC61I6mO8tsveroa7q+1GPmzhcJ9zeJ6SJuTyP7DCBJSWzxtx57AMZUfowKWAKt1kihyjd3Iy/m2bj84SXGlq+JZZG+zT4+ZmAHdWAT/rE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
