travis:
  secure:
    BINSTAR_TOKEN: jUTjPpfgw5HTKXf8lr3+yMabL5B/fV1nlMVJ2AgX5wjuUtbeR0H1nP8FRkTmXc9VGhYkt6DLUwmKAiQnphxn59HT9rXKOr/h5VYc8GU79bdzLedjW7NwOWWUUJF/npXt0MD31TV5NSOKrHdrl59Q0uqTJq/ZauGlQuof1+304T+DyXMhlhte+quaDKnX2bQE9MV8P8zbT4UEtZR5q0EZJbFusrEYOPwd/9R4ERsvalFrQv3m8kQtpVA4jVtWs/d7VMm80uhfIm5zIWuK6NYHG5CHDX1r7bIxpQuqFr57nxxYsG22UU35yoY2DpPdiLpvXLuo/2rYGwtjB8mQzpfS0KBLOzF7hXD1yIUFx9P8opqrSnY9CoYUWJwavqM/B4hqzmTy1oPBfqvPUrguMXYSxsT6KB2g0+cj6tgIKWhA49mANHyUAWrPkoZvSXUjGe4YmMpq3O8pBx+XbWp8x+5aGfPxAUt7riL9lMNJdc1PPaZwc1lbZ+fGAFqjUHQYQWRrOipG1WQO/DU72FN+lwQJS6QOAs1v+i2HdZ2HOTffoTgu6yLhYuF0poKzZiYGA2SaX5arq+OAuDt0x3NHLiRc4WfQpztjXTDcsQjdNSWmJdvmPHS3nooirvx78CvF/emL8VCdOyb6UDZ8NoQHTMPqH751S6cYQIAyclme/n9Okto=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
