travis:
  secure:
    BINSTAR_TOKEN: OORI/GUcwAZTZlwOZe4e1puYAj5TvqO1cni2sRdnldsd8BPQ3o7Qh1es2tdm8VvTWFfpiu+v4NsBsteswIM0QDki8lLPi6CS6cPzJASkT5ZcQ1RK0HO3KOEjV2Ypc8EQOEVW9OZevxShzLg0sJkKlc1PufkefiHRh/VgRl3QqdizGP5lmstfRd0JxJg21LqVPCKRRsyT/WhW4j4N411TOmf4CRGMlbqdQcXwMH4UMxLmM5fHGG+k8Nppv1ofhvP07b8gQJR7CX2l9bXzajGrESKoqG8/Zxo9wqVRUhbgcmKSNucB4i/ldv/cxA1uGxgAh0Y668uaywthXM+9VU8DH2BylToNiqsE+IhMSMH4XetcJx/P8A/7/SRXUvCHXfSLjxqBrvqo+gu2M/ZplzYKyJ5urLUz1Dp0Mjw0BsxLmabGLjK68qmoPH9YIXpiuMZAayPlFlxREVpRAeoRx5ZUur16IP2qxGVVYr+oHS8uV96sHsN5ms5gm4w4gD73yREaoVMgRHchoeGb3iFT0OkmMFLBjKUfpVFDp3cjgIAE3fDGp6R1TNpQpnbqn8vuiFzkm1kfsifxqdx3cIb9IVfoJ3yAZo9BsfzxfPjD5UZMdFGNpNd7eOkAmIp9bL3EwPfJZhQqBAkYM2ZW23+wipbRnFA1+aSyeaS/seAGdxnv1i4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
